# Run with
# ansible-playbook fresh-storage.yml -i inventory/home/hosts.ini
# https://github.com/gdha/pi4-longhorn/tree/main/prepare-usb-disk
---

- name: Configure storage as new
  hosts: k3s_cluster
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - format_usb_device